[package]
name = "rocket_authifier"
version = "1.0.15"
edition = "2021"
license = "Apache-2.0"
authors = ["Pawel Makles <me@insrt.uk>"]
description = "rocket.rs implementation of authifier"
repository = "https://github.com/authifier/authifier"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
utoipa-scalar = { version = "0.3.0", features = ["rocket"] }
mongodb = { version = "3.1" }
async-std = { version = "1.9.0", features = [
    "tokio02",
    "tokio1",
    "attributes",
] }
authifier = { version = "1.0.15", path = "../authifier", features = [
    "rocket_impl",
    "utoipa",
    "async-std-runtime",
    "database-mongodb",
] }
reqwest = { version = "0.11.10", features = ["json"] }
serde_json = { version = "1.0.81" }
regex = { version = "1.5.6" }
chrono = { version = "0.4.19" }

[dependencies]
authifier = { version = "1.0.15", path = "../authifier", features = [
    "rocket_impl",
    "utoipa",
] }

# Rocket
rocket = { version = "0.5.1", default-features = false, features = ["json"] }
rocket_empty = { version = "0.1.2", features = ["schema"] }

# Serde
iso8601-timestamp = { version = "0.2.10" }
serde = { version = "1.0.116", features = ["derive"] }

# Schemas
utoipa = { version = "5.4.0", features = ["rocket_extras"] }
